name: Format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Check formatting
        run: zig fmt --check src/
